# Generated by Django 4.2.16 on 2025-07-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_uuid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Балланс')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
